[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Vamos a crear Viade, un sistema de gestión de rutas descentralizado basado en las especificaciones Solid.

Los usuarios de la aplicación podrán crear rutas y decidir con quien comparten esas rutas.

Para realizar el sistema se utilizará el framework React.
****

=== Requirements Overview

[role="arc42help"]
****
.Funcionales
* El sistema se basará en una arquitectura descentralizada para que los datos estén separados de la aplicación.
* Los usuarios podrán visualizar las rutas en una mapa.
* Los usuarios podrán almacenar las rutas en sus propios pods.
* Se permitirá al usuario compartir fotos, vídeos o otro tipo de ficheros con amigos, y podrá crear grupos con estos.
* Un usuario podrá obtener notificaciones cuando otro usuario quiera compartir una ruta con él.


.No Funcionales
* Seguridad de la información de los usuarios usando datos descentralizados.
* Sistema usable para todo tipo de usuarios.
* El sistema debe ser capaz de operar adecuadamente con varias sesiones simultáneas.
* El sistema debe ser compatible con otros sistemas de gestión de rutas.

****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
