[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

[options="header",cols="2,2"]
|===
|Constraint|Explanation
| Usar el framework React | Sera necesario aprender a usar React 
| Usar la arquitectura Solid | Sera necesario aprender como es la arquitectura Solid
| Usar una base de datos descentralizada | Tendremos que aprender a crear y trabajar con bases de datos descentralizadas 
| Usar GIT | Tendremos que acostumbrarnos a utilizar GIT 
| Trabajar con una API de mapas | Sera necesario utilizar una API de mapas para la aplicacion, teniendo que escoger la que creamos mas conveniente.
|===