[[section-runtime-view]]
== Runtime View




A continuación, se mostrarán diagramas para poder ver la interacción que espera tener la aplicación en distintos escenarios.



=== Login en Solid
Cuando un usuario intente logearse en nuestro sistema deberá iniciar sesion con unas credenciales (por lo que necesitara
un POD) que serán validados por SOLID, despues de esta validación SOLID aceptará o rechazará la petición de logeo.


----
Usuario -> SOLID: Peticion de autenticación
SOLID -> BBDD(POD): Validación de datos
POD_BBDD -> SOLID: Respuesta a la validación
SOLID --> Usuario: Respuesta a la autenticación
----



=== Ver rutas de un usuario

Cuando usuario(Autenticado) quiera ver sus rutas la aplicación se encargará de conectarse al POD del usuario y devolvera una vista con las rutas listadas siguiendo un criterio determinado.
  

----
Usuario_X -> APP: Solicitar listado de rutas
APP -> BBDD(POD de X): Solicitar las rutas al POD
POD_de_X_BBDD -> APP: Devuelve las rutas en formato JSON (Ejemplo)
APP -> APP: Genera unas vista a partir del JSON recibido
APP -> Usuario: Envia la vista de la rutas generada
----

=== Ver lista de amigos
Para ver la lista de amigos de un usuario, se introducirá en la aplicación el nombre del usuario del que queremos obtener la lista y la aplicación generará una interfaz con dicha lista.

----
Usuario -> APP: Solicita el listado de amigos
Usuario -> APP: Proporciona usuario actual
APP -> BBDD(POD) Solicita la lista de amigos del usuario pasado
BBDD_POD_ -> APP: Devuelve la lista de amigos
APP -> APP: Genera la vista a partir de la lista
APP -> Usuario: Responde con la interfaz solicitad
----